### ISSUE TITLE
Uncaught TypeError: this.editor.getBuffer is not a function

### ISSUE THREAD

**Issue by lmplmplmp** [edda/cucumber-atom#18]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [cucumber](https://github.com/edda/cucumber-atom) package 0.6.0

### Stack Trace

Uncaught TypeError: this.editor.getBuffer is not a function

```
At C:\Users\lmp\.atom\packages\cucumber\lib\cucumber.coffee:63

TypeError: this.editor.getBuffer is not a function
    at Cucumber.module.exports.Cucumber.alignTableCells (/packages/cucumber/lib/cucumber.coffee:63:24)
    at Object.alignTableCells (/packages/cucumber/lib/main.coffee:17:14)
    at /packages/cucumber/lib/main.coffee:9:77)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:1314:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:48.3.0 core:paste (input.hidden-input)
  3x -0:46.2.0 core:backspace (input.hidden-input)
     -0:44.8.0 core:move-down (input.hidden-input)
  5x -0:44.4.0 core:backspace (input.hidden-input)
  2x -0:37.2.0 editor:newline (input.hidden-input)
     -0:06.9.0 cucumber:align-table-cells (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
asciidoc-preview 2.10.2 
cucumber 0.6.0 
```

**Comment by uLucasFraga** [comment]
any updates here?
